<a href="https://colab.research.google.com/github/abekpudo/my-ml-zoomcamp/blob/main/Module_1_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

In [2]:
# Q1 - Pandas version
pd.__version__

'2.2.3'

In [60]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  object
 2   fuel_type            10000 non-null  object
 3   drivetrain           10000 non-null  object
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), object(3)
memory usage: 859.5+ KB

In [64]:
# Q2 - Records count
df.shape[0]

10000

In [65]:
# Q3 - Number of fuel types
df['fuel_type'].nunique()

3

In [20]:
# Q4 - Missing values
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [59]:
# Q5 - Maximum fuel efficiency of cars from Asia
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

41.2

In [39]:
# Q6
hp = df['horsepower']

# [Step 1] median value of horsepower (with missing values)
med_hp = hp.median()
print(f'Median value of horsepower (with missing values):\n {med_hp}')

# [Step 2] most frequent value of horsepower (with missing values)
mfv_hp = hp.mode()
print(f'\nMost frequent value of horsepower (with missing values):\n {mfv_hp}')

# [Step 3] fill missing values with most frequent value
hp.fillna(mfv_hp, inplace=True)

# [Step 4] median value of horsepower (after filling missing values)
med_hp = hp.median()
print(f'\nMedian value of horsepower (after filling missing values):\n {med_hp}')

Median value of horsepower (with missing values):
 254.0

Most frequent value of horsepower (with missing values):
 0    252.0
Name: horsepower, dtype: float64

Median value of horsepower (after filling missing values):
 254.0

In [41]:
# Q7
# [Step 1] Select all cars from Asia
asia = df[df['origin'] == 'Asia']

asia.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [43]:
# [Step 2] Select only vehicle_weight and model_year columns
asia_df = asia[['vehicle_weight', 'model_year']]

asia_df.head()

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007

In [44]:
# [Step 3] Select first 7 values
asia_7 = asia_df.iloc[:7]

asia_7.head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [46]:
# [Step 4] Get the underlying numpy array
X = asia_7.to_numpy()

X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [47]:
# [Step 5a] Transpose X
XT = X.T

XT

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [48]:
# [Step 5b] matrix-matrix multiplication between X and XT
XTX = np.dot(XT, X)

XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [49]:
# [Step 6] Invert XTX
XTX_inv = np.linalg.inv(XTX)

XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [50]:
# [Step 7] Create array y
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [51]:
# [Step 8] Multiply the inverse of XTX with the transpose of X, and then multiply the result by y
w = np.dot(np.dot(XTX_inv, XT), y)

w

array([0.13644777, 0.2327492 ])

In [52]:
# [Step 9] Sum of w
w.sum()

np.float64(0.36919696904925486)